# Dependabot will check our GitHub actions and if there will be a new version of any action
# Dependabot will create a pull request to update these.
#
# FIXME: Unfortunately, the Dependabot is checking only the default branch right now.
#        Could be solved by https://github.com/dependabot/dependabot-core/issues/2511.

# Set update schedule for GitHub Actions
version: 2
updates:

  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      # Check for updates to GitHub Actions every weekday
      interval: "daily"
    commit-message:
      prefix: "infra"
    labels:
      - "infrastructure"
      - "manual testing required"

  # FIXME: Update our npm development dependencies monthly.
  # See: https://github.com/dependabot/dependabot-core/issues/2390
  - package-ecosystem: "npm"
    directory: "/ui/webui"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "infra"
    labels:
      - "sanity check required"
