# Dependabot checks our dependencies and opens pull requests for new versions.
# See the current status: https://github.com/rhinstaller/anaconda/network/updates

# FIXME: Unfortunately, Dependabot is checking only the default branch right now.
#        See: https://github.com/dependabot/dependabot-core/issues/2511

version: 2
updates:

  # Set update schedule for GitHub actions.
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "infra"
    labels:
      - "infrastructure"

  # Set update schedule for npm packages.
  # FIXME: Update our npm development dependencies monthly.
  # See: https://github.com/dependabot/dependabot-core/issues/2390
  - package-ecosystem: "npm"
    directory: "/ui/webui"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "infra"
    labels:
      - "sanity check required"

  # Set update schedule for pip in containers
  - package-ecosystem: "pip"
    directory: "/dockerfile"
    schedule:
      interval: "weekly"
    commit-message:
      prefix: "infra"
    labels:
      - "infrastructure"
      - "sanity check required"
