name: Add PR labels automatically
on:
  pull_request:
    types: [opened]

permissions:
  contents: read
  pull-requests: write

jobs:
  add-label:
    runs-on: ubuntu-20.04
    steps:
      - name: Add labels
        uses: actions/labeler@v4
