name: Refresh container images
on:
  schedule:
    - cron: 0 0 * * *
  # be able to start this action manually from a actions tab when needed
  workflow_dispatch:

jobs:
  refresh-container:
    name: Refresh anaconda-ci container
    runs-on: ubuntu-20.04
    # we need to have matrix to cover all branches because schedule is run only on default branch
    # we can add here fedora branches (e.g. f33-devel) to cover their support when needed
    strategy:
      matrix:
        branch:
          - master
    timeout-minutes: 60
    steps:
      - name: Checkout anaconda repository
        uses: actions/checkout@v2
        with:
          ref: ${{ matrix.branch }}

      - name: Build anaconda-ci container
        run: make -f Makefile.am anaconda-ci-build

      - name: Run tests in anaconda-ci container
        id: run-tests
        run: |
          # put the log in the output, where it's easy to read and link to
          make -f Makefile.am container-ci || { cat test-logs/test-suite.log; exit 1; }

      - name: Upload test and coverage logs from local testing
        if: always()
        uses: actions/upload-artifact@v2
        with:
          name: logs
          path: |
            tests/test-suite.log
            tests/nosetests.log
            tests/pylint/runpylint*.log
            tests/coverage-*.log

      - name: Login to container registry
        run: podman login -u ${{ secrets.QUAY_USERNAME }} -p ${{ secrets.QUAY_PASSWORD }} quay.io

        # we can hardcode the path to the image here because this will be executed only for master image
      - name: Add latest tag for master branch
        if: ${{ matrix.branch == 'master' }}
        run: |
          podman tag quay.io/rhinstaller/anaconda-ci:master quay.io/rhinstaller/anaconda-ci:latest
          CI_TAG=latest make -f Makefile.am anaconda-ci-push

      - name: Push container to registry
        run: make -f Makefile.am anaconda-ci-push
